### ISSUE TITLE
Missing PodsGPT reference framework or podfile

### ISSUE THREAD

**Issue by sea-and-kai** [wykeenjenga/ChatGPT#1]
It looks like there's a cocoapods ChatGPT framework needed for this repo yet there is no podfile and no Pods folder containing a previously downloaded version.

**Comment by wykeenjenga** [comment]
Hey kai you are supposed to install all the necessary library

**Comment by daniellefisla** [comment]
I am having similar issues building this, can you specify which versions of the libraries you were able to successfully compile the app with?

**Comment by wykeenjenga** [comment]
Hey, @daniellefisla if possible can you share the exact error you’re getting or a screenshot please?

**Comment by daniellefisla** [comment]
@wykeenjenga I think knowing the exact versions of packages you are using for depedencies could solve this.

Build errors:
<img width="338" alt="Screenshot 2023-02-04 at 6 05 02 PM" src="https://user-images.githubusercontent.com/66973302/216793239-610ccf55-c56c-4327-b60b-f737a8168840.png">

My dependencies:
<img width="273" alt="Screenshot 2023-02-04 at 6 06 24 PM" src="https://user-images.githubusercontent.com/66973302/216793264-a811b51f-ebc6-48a9-bc10-e70c3e7ec600.png">

**Comment by wykeenjenga** [comment]
Aaah great! I can see it's not pods or a library. Please troubleshoot further and see what might be the issue with your code or just clone the project again. Those are syntax errors which are easy to solve incase you need any further assistance please lemme know via wycliffnjenga19@gmail.com.
Thanks.
